[module/cput]
type = custom/script
label = Cpu %output:0:15:%
exec = ~/.config/polybar/scripts/cpu_temp.sh
;Exec = sensors | awk '/^Tctl:/ {print $2}' 
interval = 5
format-prefix = " "
format-prefix-foreground = #c1941a
format-underline = #c1941a
format-padding = 1
format-foreground = ${colors.foreground}
format-background = ${colors.background}

