#!/usr/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x mopidy > /dev/null || mopidy &

$HOME/.config/polybar/launch.sh


bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

wmname LG3D

bspc rule -a Gnome-calculator state=floating


